### ISSUE TITLE
rpy2 required for change detection analysis

### ISSUE THREAD

**Issue by LisaHopcroft** [opensafely-core/python-docker#23]
We are hoping to run the [change detection code] (https://github.com/ebmdatalab/change_detection) in [PINCER] (https://github.com/opensafely/pincer-measures/tree/indicator-saturation-analysis). This requires rpy2 (geopandas is already included). Could this be installed please? /cc @LFISHER7

**Comment by bloodearnest** [comment]
rpy2 requires r installed. We cannot install R into the python image, as it would make it too big, and most users do not use this.

**Comment by bloodearnest** [comment]
Am closing this, as I think we're doing it differently.
