### ISSUE TITLE
Not calling `python` breaks on Windows

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/python-docker#37]
Calling this

```
python:latest analysis/my_script.py
```

should be equivalent to calling this

```
python:latest python analysis/my_script.py
```

because [if the user provides their own executable, then we call it][1] in preference to `python`, which is [the default on python-docker][2]. On Windows, however, all files are executable. Consequently, the former will break when run on the TPP backend (but it will work locally, if the user is running macOS, as @LindaNab discovered).

Background in [this Slack thread][3].

[1]: https://github.com/opensafely-core/base-docker/blob/8a13fbbb5e1e2595c7e844527a637a44df253a4d/entrypoint.sh#L8-L9
[2]: https://github.com/opensafely-core/python-docker/blob/83b2e08bcb51ffd387bd32e5c0b577c770af322e/Dockerfile#L57-L58
[3]: https://ebmdatalab.slack.com/archives/C63UXGB8E/p1648039500754909

**Comment by evansd** [comment]
This should hopefully be fixed by:
 * https://github.com/opensafely-core/base-docker/pull/21

Once that's merged and this image is rebuilt from the new base we should confirm that this is fixed and close if we can.

**Comment by bloodearnest** [comment]
Tested with the new base-action, it works, so rebuilt this image.
