### ISSUE TITLE
Add UpsetPlot

### ISSUE THREAD

**Issue by robinyjpark** [opensafely-core/python-docker#43]
Upset plots are useful for visualising overlaps between combinations. We plan to incorporate them into the standard derived data plausibility checking template to summarise overlaps in combinations of phenotypes variables. 

Package: https://pypi.org/project/UpSetPlot/
Documentation: https://upsetplot.readthedocs.io/en/stable/

**Comment by andrewscolm** [comment]
Having tried this out locally it looks like it would be really useful / informative.

**Comment by robinyjpark** [comment]
Here is an example on dummy data, showing the intersection across 4 different phenotype variables. Would be really useful for any phenotype variable validation report with more than two variables.  

<img width="456" alt="Screen Shot 2022-04-27 at 6 02 42 PM" src="https://user-images.githubusercontent.com/72387969/165580380-c51ecabf-3d89-470c-b0ed-7352e4a55659.png">
