### ISSUE TITLE
Update matplotlib to 3.5+

### ISSUE THREAD

**Issue by ccunningham101** [opensafely-core/python-docker#85]
The image currently has [matplotlib version 3.1.1](https://github.com/opensafely-core/python-docker/blob/main/requirements.txt#L167-L174) from 2019, but a beta feature in 3.4 for subplots, and a full feature in 3.6 is [constrained layout](https://matplotlib.org/stable/tutorials/intermediate/constrainedlayout_guide.html), which is an improvement upon tight_layout. 

When creating a panel plot for demographic breakdowns, the size of the legends for the demographic groups vary considerably (from Male/Female to East, East Midlands, London, Northeast, Northwest, Southeast, Southwest, West Midlands, Yorkshire and the Humber). Region cannot fit on the plot without covering up data and still being readable. Constrained layout is extremely helpful both for fitting legends outside the plot when tight_layout would cut them off, and automatically maintaining reasonable space between the subplots so it doesn't have to be manually specified for each plot.

This [PR ](https://github.com/opensafely/antidepressant-prescribing-lda/pull/31/commits/3adb3b3259dcf9180e154385d4667747e9375451) implements constrained layout using matplotlib 3.5. 

Matplotlib 3.6 [still supports](https://github.com/matplotlib/matplotlib/blob/v3.6.2-doc/tox.ini#L7) python 3.8
Matplotlib 3.6 requires numpy 1.19 (image is at 1.18), but 3.5 would be sufficient for constrained layout

**Comment by andrewscolm** [comment]
Update: we have had a pilot request to update to at least version 3.4 so that the `bar_plot` function can be used.

**Comment by StevenMaude** [comment]
The `v2` Python image now has [Matplotlib 3.8.2](https://github.com/opensafely-core/python-docker/blob/7946e88aff14ec2938f06f3d9a2403675db15fa7/v2/requirements.txt).
